<Project>
  <PropertyGroup>
    <PackageVersion_GodotSharp>26.2.0</PackageVersion_GodotSharp>
    <PackageVersion_Godot_NET_Sdk>26.2.0</PackageVersion_Godot_NET_Sdk>
    <PackageVersion_Godot_SourceGenerators>26.2.0</PackageVersion_Godot_SourceGenerators>
    <GodotVersionConstants>GODOT26;GODOT26_2;GODOT26_2_0;GODOT4_OR_GREATER;GODOT5_OR_GREATER;GODOT6_OR_GREATER;GODOT7_OR_GREATER;GODOT8_OR_GREATER;GODOT9_OR_GREATER;GODOT10_OR_GREATER;GODOT11_OR_GREATER;GODOT12_OR_GREATER;GODOT13_OR_GREATER;GODOT14_OR_GREATER;GODOT15_OR_GREATER;GODOT16_OR_GREATER;GODOT17_OR_GREATER;GODOT18_OR_GREATER;GODOT19_OR_GREATER;GODOT20_OR_GREATER;GODOT21_OR_GREATER;GODOT22_OR_GREATER;GODOT23_OR_GREATER;GODOT24_OR_GREATER;GODOT25_OR_GREATER;GODOT26_OR_GREATER;GODOT26_0_OR_GREATER;GODOT26_1_OR_GREATER;GODOT26_2_OR_GREATER;GODOT26_2_0_OR_GREATER</GodotVersionConstants>
  </PropertyGroup>
</Project>
